FROM node:lts-alpine

RUN mkdir -p /usr/src/app/frontend
WORKDIR /usr/src/app

COPY ./package.json /usr/src/app
COPY ./yarn.lock /usr/src/app
COPY ./frontend/.env /usr/src/app

RUN yarn install --pure-lockfile

EXPOSE 3000
CMD [ "yarn", "frontend:dev" ]