version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./services/api/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: 'production'
    ports:
      - 5000:5000
    networks:
      - mspmr_net
    depends_on:
      - mongodb
      - redis
      - rabbitmq

  twitch-listener:
    build:
      context: ./
      dockerfile: ./services/twitch-listener/Dockerfile
    restart: "no"
    networks:
      - mspmr_net
    depends_on:
      - api

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV: 'production'
    ports:
      - 3000:3000
    networks:
      - mspmr_net
    depends_on:
      - api