version: '3.8'

services:

  mysql:
    image: mysql:debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mspmr
      MYSQL_USER: mspmr
      MYSQL_PASSWORD: changeme
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mspmr_net

volumes:
  mysql_data:

networks:
  mspmr_net:
    driver: bridge