version: '3.8'

services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mspmr_net
  
  adminmongo:
    image: mrvautin/adminmongo:latest
    restart: always
    ports:
      - 11234:1234
    environment:
      HOST: "0.0.0.0"
      CONN_NAME: mspmr
      DB_HOST: mongodb
    networks:
      - mspmr_net
    depends_on:
      - mongodb
  
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - mspmr_net

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: changeme
    networks:
      - mspmr_net

volumes:
  mongodb_data:

networks:
  mspmr_net:
    driver: bridge